[package]
name = "search_and_destroy_chess_2"
version = "0.3.0"
edition = "2018"

[dependencies]
find_folder = "0.3.0"
#sdl2 = "0.35.1"
#ggez = "0.7.0"
sfml = "0.16.0"
rand = "0.8.4"
regex = "1.5.4"
# piston_window = "0.120.0"
