# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
  pull_request:

name: run

jobs:
  run:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy

      # Do not run, as there are graphics
      #- name: run
      #  uses: actions-rs/cargo@v1
      #  with:
      #    command: run

